### ISSUE TITLE
undefined method `name_id' for #<struct request_id=nil>

### ISSUE THREAD

**Issue by masa-ekohe** [saml-idp/saml_idp#129]
When I try to logout via a link on my service provider, the idp rails app throws 500 saying `undefined method 'name_id' for #<struct request_id=nil>`.

versions:
```
ruby 2.4.1
rails 5.2.3
saml_idp 0.8.0
```

log:
```
I, [2020-04-23T06:09:47.614360 #4086]  INFO -- : [275a4a9f-38f1-45a3-bd46-75eee09441c9] Started POST "/saml/logout" for 118.86.255.213 at 2020-04-23 06:09:47 +0000
I, [2020-04-23T06:09:47.617226 #4086]  INFO -- : [275a4a9f-38f1-45a3-bd46-75eee09441c9] Processing by SamlIdpController#logout as HTML
I, [2020-04-23T06:09:47.617365 #4086]  INFO -- : [275a4a9f-38f1-45a3-bd46-75eee09441c9]   Parameters: {"SAMLRequest"=>"PD94bWwgdmVyc2lvbj0iMS4wIj8+CjxuczA6TG9nb3V0UmVxdWVzdCB4bWxuczpuczA9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpwcm90b2NvbCIgeG1sbnM6bnMxPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIiB4bWxuczpuczI9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiIElEPSJpZC12YmNrbjJPaWNhYnNTQjZweCIgVmVyc2lvbj0iMi4wIiBJc3N1ZUluc3RhbnQ9IjIwMjAtMDQtMjNUMDY6MDk6NDdaIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly93d3cuZ2xvYmFsaW5ub3ZhdGlvbmV4Y2hhbmdlLm9yZy9zYW1sL2xvZ291dCIgUmVhc29uPSIiPjxuczE6SXNzdWVyIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5Ij5odHRwczovL2lubm92YXRpb25zLnNtYXBwbHkuaW8vc2FtbDIvbWV0YWRhdGEvPC9uczE6SXNzdWVyPjxuczI6U2lnbmF0dXJlIElkPSJTaWduYXR1cmUxIj48bnMyOlNpZ25lZEluZm8+PG5zMjpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8+PG5zMjpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjcnNhLXNoYTEiLz48bnMyOlJlZmVyZW5jZSBVUkk9IiNpZC12YmNrbjJPaWNhYnNTQjZweCI+PG5zMjpUcmFuc2Zvcm1zPjxuczI6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiLz48bnMyOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvbnMyOlRyYW5zZm9ybXM+PG5zMjpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPjxuczI6RGlnZXN0VmFsdWU+dHJIWXcyYlFzeWpGQldHNHIxbFRsVzNQT2lVPTwvbnMyOkRpZ2VzdFZhbHVlPjwvbnMyOlJlZmVyZW5jZT48L25zMjpTaWduZWRJbmZvPjxuczI6U2lnbmF0dXJlVmFsdWU+WGxrTzJBVUMvMHZRbkZ4aEUrVUhaM2tjdTdxaE1obkRRVEtBaE1ZajVMWFlOMEdNT08zczRaUnpQSnZzaXZjawpPUTMyWHJ6cVhXSVpqcmxBeHVRSVNkSW1jWjlYUHFlTk9FWEJYVUV3akZJdzcwandTMVhJUlArb0RsYVBadEF1CjV1cWlSdk1FbkJsOG1HQXFwVnpLSkFhdW9lS3ZPOHE3RzZDNGNINlN4NUtXUlh1eFBVKzljbWYwcEpnVFdtYXQKdDVZMWllSWVoTHpIemlqYmQzeVpYeUZMYjBybGpQYnlwWWJSNk1IWWRzSmxtekw5ME9YVmJjRFNUUVJKSzNJZwpLOUZRSWdMSmM3czFhZk12N1NxTEJ0TnN3cFhxODBuYnJXVHMwYVpGOFYyWkFWdnlsWlpPTFZOMWJQU28yRHhRClN2eHdCa29zRFpXdkMvY3ZRdjM3b2UyYzRLVHhndzRhajBKcCtYb2dRU0JGOUJIcm5TZjBOQWJLaUFnY1JESjMKeHpsakt2YUFCNkpWOWxKeUthMDJtZ2QzV0cyTjdBcHkzNEpLZkJRSTFLc3MrcXE0MG9BbTJEYXdwNS9TaXB1ZQpOM1pJYmZ1cjRsbWU5SldhYng4M3oybWZRVzExRWJZQ0FEbjV3RktIQkJ2dFFIOHRSQkd4ZndSME15Z2E5b0xpCk5tL0VxYVNtT3VuK295ejhjVURSV2ltWHdPc2ZBR1BXU3dIZ251Y2lmL2VYZyt2QWIxWldNNHQ2cm0zMXlVMWwKRnFLVjVwSDRSQkltTnpTaWQyYkpjRkxsNFZhM3lUVGZ6eDlmWGF0a2orb0ZUWjRsWU1LSVpTaXJMVDN4RDBwNwpHTDY1bjMwa1hQZW16Z2ZBaHBxSXFNSVBGZjd4Q0ExR0dvU1ZrT2YvaFFRPTwvbnMyOlNpZ25hdHVyZVZhbHVlPjxuczI6S2V5SW5mbz48bnMyOlg1MDlEYXRhPjxuczI6WDUwOUNlcnRpZmljYXRlPk1JSUZ0ekNDQTUrZ0F3SUJBZ0lKQU41OWJMdVQ1MEUzTUEwR0NTcUdTSWIzRFFFQkN3VUFNSEl4Q3pBSkJnTlZCQVlUQWtOQk1Rc3dDUVlEVlFRSURBSlBUakVWTUJNR0ExVUVDZ3dNVTNWeWRtVjVUVzl1YTJWNU1SZ3dGZ1lEVlFRRERBOW1iSFZwWkhKbGRtbGxkeTVqYjIweEpUQWpCZ2txaGtpRzl3MEJDUUVXRm01aGRHVmlRSE4xY25abGVXMXZibXRsZVM1amIyMHdIaGNOTVRZeE1qRTVNakV5TWpNd1doY05Nall4TWpFM01qRXlNak13V2pCeU1Rc3dDUVlEVlFRR0V3SkRRVEVMTUFrR0ExVUVDQXdDVDA0eEZUQVRCZ05WQkFvTURGTjFjblpsZVUxdmJtdGxlVEVZTUJZR0ExVUVBd3dQWm14MWFXUnlaWFpwWlhjdVkyOXRNU1V3SXdZSktvWklodmNOQVFrQkZoWnVZWFJsWWtCemRYSjJaWGx0YjI1clpYa3VZMjl0TUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF4bTVmVnFzOW5XYitKdCtOVitNYlp2eU9zdEY1YUJqbXJ1UnBBbEQ4bW54ZmM1S1JFdVZHYkNudWF4ZHFSb1ZUcnlseldwUEU1My9hSUFna2hOWUxaeSswVFBVQnNpZ29IME5GWDdZQmp2WlhFaE16QXF0aFVPYTJ2djFLZWlTbGhUMTl4akU1TGR0SDVtUHhEVFZZdkFHM0UwbXVqQVZ5NlA2Y20wQ3JtcVVvVUhueHZmMTVXWlcwNUlxbk1uWExEVkpWcEpHVk5ZSFhZTDEvZUxidzFlSUZsQXFianFGTVI4cjEweDBDdmlVL3NGWURFU1JQNzZrdmU5NEFuYnFhK0tBeU0yNTJNU2Mvck9LNnh5ajhaM3lkQ09JRC9nRUM0WnR4K1pPUk95eVVhWTZJMll4ZnpuT2x3MWhqYVJ6SUR4Z2JQeXRTRVVpK0VjTk8xWmJJVGFXa3llQlhkTmRBKzhXbm5MWFBpTkNFWmF0aGVWbzdwbmdIaDZsbzFnWTJUWnNOZjA4M1lNc05GbW41TUgxSTdGblVNSWc1S0NnbllMTGZCb1pNWjhHZllGcVVYSGZFOTE3WENxT29FVnBFVmxJVHZlZVMweFQ5bU5JaG1WaE03cHJldVNzeGFBdVFVNjFKSUViZFk0M1BpZUxwUkpnQnQ0MmNuYUN2aFpYSHNDei9lWmhxN2lleFQ0Z3JYN0JxeEhJaS9TencwV1VmdzZJeU1lOHVxNGEvbEpHKzRhWkYxR2N1T0lBLzYvNnBlTGRyVys3RVpmM2pmZ0cyMXpYUWpxUVlSVUE3ci9GS3dFR0luaEk5QmU3SVhWZ2FGUXlXV2dBMVVObEJpaDVMcW9KYTBFeURTQnFZeDE0OTRYZStIVDFSZ1k5UitxdVBKS0Uxbk1lMi9Zc0NBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGT1F2Qy9jMUc2U2tHbGV4bDJPMG5YS1JVOHJRTUI4R0ExVWRJd1FZTUJhQUZPUXZDL2MxRzZTa0dsZXhsMk8wblhLUlU4clFNQXdHQTFVZEV3UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFDUEdsNUJxVVZzQUFNM0c4ODB0RXFlMk5IdFcydzIxcHdETnRZLzgvZkVFdlBkeDc0YkFVc3RVTDhFelhSYzR4bUxmOS9zcFpTcmR3alJVWjBldDVmWDNLOXA3MnVtdHdmVk00NG52V2VVK1VvUVkwVjYzYUI0U1lBRFhRbytnd3lCZmZsV2hSWkpCdHZnK1N2NmJaOUNaZHNKM2RtTDM4WjNWM2dIY0dhS2s5UDdkUmI5a2VvSkNZRjFGOHQyM2VKZW00QmRFSzhCMERjV0JNVVFjT2RjZHNlbHIzUFpIekxiakUxQXVMYVFWZk1Ua3NWbzErUi9jZDFOaGF3aDlIaFkwRjdzcVc2VWl3NkJ6dTRVTmR6NldjV1Z6TnNJdkZLMmxNcVl3Zkx5N0haWFlyRENKNVY1N2NCQXZRN2hocUY4K2FOdS9nR1dnVXA3Q1ZBRWhHZGtuV202VWtMM1VNUUlvdG04Q3RXN0krZHJBYmVvbFVJSktNQTM0N1ZOcytKREM3d3FLSkozT0xkS2tTdFVzRVNocXFjcXRFb05NZDFkM2dtOU1vUlBPTm40cklpYWVuVnFtT1djVklBWW9CVFJjQVdiV2d5cjB4ZXNqSjlESWdHT3Z3eG1KSmk0RWpuTHVRWEVpQ29VbjlaM3pveTZ2MnBjRGsvUjcyV01YUmpFUmZyMk1GQ1E3VlBqSWRZWTRoZVM5TzVjWnI5bnNlN2pSTUljK3locjI4RHpOSWZmQk9CZjdTT2hHSFllemc4dmNUNFZrU1ZpWWdneElGUEROdTZ1dFVBQTFoWTNUZDFQNjQxY3NKSzZyYkFTd29ReTFhTituQzFLclRRTmNmaE0wRnJvUENXZ1lDVGNnWHdUMTMzOG1scktYenV4bXRlRkpHVzV1eHM0NjwvbnMyOlg1MDlDZXJ0aWZpY2F0ZT48L25zMjpYNTA5RGF0YT48L25zMjpLZXlJbmZvPjwvbnMyOlNpZ25hdHVyZT48bnMxOk5hbWVJRCBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpuYW1laWQtZm9ybWF0OmVtYWlsIj5tYXNha2F6dUBla29oZS5jb208L25zMTpOYW1lSUQ+PG5zMDpTZXNzaW9uSW5kZXg+X2YwZDUzNDQwLTY3NTYtMDEzOC0zM2QzLTBlNjQ4OTYzM2UwMDwvbnMwOlNlc3Npb25JbmRleD48L25zMDpMb2dvdXRSZXF1ZXN0Pgo=", "RelayState"=>"id-vbckn2OicabsSB6px|1587622187|ef38f521560c49d481e7da6ba71bcda6c509a283"}

I, [2020-04-23T06:09:47.628511 #4086]  INFO -- : [275a4a9f-38f1-45a3-bd46-75eee09441c9] Completed 500 Internal Server Error in 11ms (ActiveRecord: 1.4ms)
F, [2020-04-23T06:09:47.629469 #4086] FATAL -- : [275a4a9f-38f1-45a3-bd46-75eee09441c9]
F, [2020-04-23T06:09:47.630988 #4086] FATAL -- : [275a4a9f-38f1-45a3-bd46-75eee09441c9] NoMethodError (undefined method `name_id' for #<struct request_id=nil>):
F, [2020-04-23T06:09:47.631038 #4086] FATAL -- : [275a4a9f-38f1-45a3-bd46-75eee09441c9]
F, [2020-04-23T06:09:47.631072 #4086] FATAL -- : [275a4a9f-38f1-45a3-bd46-75eee09441c9] app/controllers/saml_idp_controller.rb:49:in `idp_logout'
[275a4a9f-38f1-45a3-bd46-75eee09441c9] app/controllers/saml_idp_controller.rb:85:in `logout'
```

*config/initializers/saml.rb*
```ruby
SamlIdp.configure do |config|
  base = $secrets.dig(:survey_monkey, :base_url)

  config.x509_certificate = <<EOS.strip
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
EOS

  config.secret_key = <<EOS
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
EOS

  # config.password = "my_secret_password"
  config.algorithm = :sha256
  config.organization_name = "..."
  config.organization_url = base
  config.base_saml_location = "#{base}/saml"
  config.reference_id_generator                                 # Default: -> { UUID.generate }
  config.single_logout_service_post_location = "#{base}/saml/logout"
  config.single_logout_service_redirect_location = "#{base}/saml/logout"
  config.attribute_service_location = "#{base}/saml/attributes"
  config.single_service_post_location = "#{base}/saml/auth"
  # config.session_expiry = 86400                                 # Default: 0 which means never

  # Principal (e.g. User) is passed in when you `encode_response`
  #
  config.name_id.formats = {                         # All 2.0
    email: -> (principal) { principal.email },
    transient: -> (principal) { principal.id },
    persistent: -> (p) { p.id },
  }

  config.technical_contact.company = "..."
  config.technical_contact.given_name = "..."
  config.technical_contact.sur_name = "..."
  config.technical_contact.telephone = ""
  config.technical_contact.email_address = "..."

  service_providers = {
    "https://innovations.smapply.io/saml2/metadata/" => {
      fingerprint: "...",
      metadata_url: "https://innovations.smapply.io/saml2/metadata/",
      response_hosts: ["..."]
    },
  }

  config.service_provider.metadata_persister = ->(identifier, settings) {
    fname = identifier.to_s.gsub(/\/|:/, "_")
    File.open Rails.root.join("public/#{fname}"), "r+b" do |f|
      Marshal.dump settings.to_h, f
    end
  }

  config.service_provider.persisted_metadata_getter = ->(identifier, service_provider) {
    fname = identifier.to_s.gsub(/\/|:/, "_")
    full_filename = Rails.root.join("public/#{fname}")
    if File.file?(full_filename)
      File.open full_filename, "rb" do |f|
        Marshal.load f
      end
    end
  }

  config.service_provider.finder = ->(issuer_or_entity_id) do
    service_providers[issuer_or_entity_id]
  end
end
```

*config/routes.rb*
```ruby
Rails.application.routes.draw do
...
 match '/saml/logout' => 'saml_idp#logout', via: [:get, :post, :delete]
...
end
```

*app/controllers/samlidp_controller.rb*
```ruby
# frozen_string_literal: true

class SamlIdpController < ApplicationController
  include SamlIdp::Controller
  SamlIdpLogger = Logger.new Rails.root.join("log/sm.log")

  protect_from_forgery prepend: true, with: :exception, except: %w(logout)

  ...

  def idp_authenticate(email, password)
    user = User.find_by(email: email)
    user && user.valid_password?(password) ? user : nil
  end
  private :idp_authenticate

  def idp_make_saml_response(found_user)
    sm_track_log found_user
    encode_response found_user
  end
  private :idp_make_saml_response

  def idp_logout
    user = User.find_by(email: saml_request.name_id)
    user.logout
  end
  private :idp_logout

  def logout
    idp_logout
    @saml_response = idp_make_saml_response(nil)
    render template: "saml_idp/idp/saml_post", layout: false
  end
end
```

**Comment by RiteshMC** [comment]
stuck in exactly the same problem. 

Any updates???

**Comment by zoi-aoba** [comment]
me too.... im crying

**Comment by mjobin-mdsol** [comment]
@Zogoo Any idea? ever had this problem?

**Comment by mjobin-mdsol** [comment]
looks like this struct will need to implement the method

https://github.com/saml-idp/saml_idp/blob/master/lib/saml_idp/controller.rb#L20-L34

seems like the logout function, as per presented by the documentation is broken.

**Comment by mjobin-mdsol** [comment]
@RiteshMC @zoi-aoba 

I got it ! the reason is because your SamlRequest is invalid.
the `struct request_id` I pointed at line 20-34 is a fallback.

with a valid request, it should create an object of type `SamlIdP::Request`

see

```
    def decode_request(raw_saml_request)
      @saml_request = Request.from_deflated_request(raw_saml_request)
    end
```

**Comment by neos-ritesh** [comment]
@mjobin-mdsol 
I am using SimpleSAMLphp as an SP.

Could you tell me what you are using for SP??

**Comment by RiteshMC** [comment]
@mjobin-mdsol 
I am using SimpleSAMLphp as an SP. It works with other IDPs. For Eg : SimpleSAMLphpIDP, Gsuite IDP etc, but doesnt work with Ruby Saml-IDP.

Could you tell me what you are using for SP??

**Comment by mjobin-mdsol** [comment]
if your SP works with other IDPs, I am thinking your problem RiteshMC could be configuration.
but at this point, I am not sure.

**Comment by zoi-aoba** [comment]
@mjobin-mdsol thanks!

**Comment by mjobin-mdsol** [comment]
do you guys get this on logout ? 
it seems the problem is this line in the `IdpController`

`      before_action :validate_saml_request, only: [:new, :create]`

it should be called for logout as well
